# Generated by Django 6.0.4 on 2026-04-17 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Indices',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sector', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Stocks',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='IndexDailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField()),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stocks.index')),
            ],
            options={
                'verbose_name_plural': 'Index Daily Prices',
                'ordering': ['-date'],
                'unique_together': {('index', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PurificationRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('period', models.CharField(max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('source_document', models.CharField(blank=True, max_length=100)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purification_ratios', to='stocks.stock')),
            ],
            options={
                'verbose_name_plural': 'Purification Ratios',
                'ordering': ['-effective_from'],
                'unique_together': {('stock', 'effective_from')},
            },
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_date', models.DateField()),
                ('dividend_type', models.CharField(choices=[('cash', 'Cash Dividend'), ('bonus', 'Bonus Shares'), ('right', 'Right Shares'), ('mixed', 'Cash + Bonus')], max_length=10)),
                ('cash_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('bonus_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('raw_dividend', models.CharField(blank=True, max_length=50)),
                ('raw_bonus', models.CharField(blank=True, max_length=100)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='stocks.stock')),
            ],
            options={
                'verbose_name_plural': 'Dividends',
                'ordering': ['-ex_date'],
                'unique_together': {('stock', 'ex_date')},
            },
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stocks.stock')),
            ],
            options={
                'verbose_name_plural': 'Daily Prices',
                'ordering': ['-date'],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
