# Generated by Django 6.0.4 on 2026-04-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sector', models.CharField(blank=True, max_length=50)),
                ('kse_100_member', models.BooleanField(default=False)),
                ('kmi_30_member', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
    ]
