# Generated by Django 6.0.4 on 2026-04-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_dailyprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyprice',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Daily Prices'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['symbol'], 'verbose_name_plural': 'Stocks'},
        ),
        migrations.RemoveField(
            model_name='dailyprice',
            name='high',
        ),
        migrations.RemoveField(
            model_name='dailyprice',
            name='low',
        ),
    ]
