# Generated by Django 6.0.4 on 2026-04-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_is_active_stock_removed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='tv_logo_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
