# Generated by Django 6.0.4 on 2026-07-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stock_tv_logo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('update_prices', 'Price Update'), ('update_dividends', 'Dividend Update'), ('process_notifications', 'Notifications')], db_index=True, max_length=30)),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('output', models.TextField(blank=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cron Logs',
                'ordering': ['-ran_at'],
                'get_latest_by': 'ran_at',
            },
        ),
    ]
