# Generated by Django 6.0.4 on 2026-04-17 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_dailyprice_options_alter_stock_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Indices',
                'ordering': ['symbol'],
            },
        ),
        migrations.RemoveField(
            model_name='stock',
            name='kmi_30_member',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='kse_100_member',
        ),
        migrations.CreateModel(
            name='IndexDailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField()),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stocks.index')),
            ],
            options={
                'verbose_name_plural': 'Index Daily Prices',
                'ordering': ['-date'],
                'unique_together': {('index', 'date')},
            },
        ),
    ]
