# Generated by Django 6.0.4 on 2026-07-06 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_cron_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('kibor_6m', models.FloatField(blank=True, null=True)),
                ('kibor_1y', models.FloatField(blank=True, null=True)),
                ('pkr_usd_rate', models.FloatField(blank=True, null=True)),
                ('kse100_forward_pe', models.FloatField(blank=True, null=True)),
                ('kse100_earnings_yield', models.FloatField(blank=True, null=True)),
                ('market_erp', models.FloatField(blank=True, null=True)),
                ('erp_signal', models.CharField(blank=True, choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], max_length=10, null=True)),
                ('source', models.CharField(default='sbp_website', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Macro Snapshots',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MacroWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('sbp_fx_reserves_usd_bn', models.FloatField(blank=True, null=True)),
                ('monthly_imports_usd_bn', models.FloatField(blank=True, null=True)),
                ('import_cover_months', models.FloatField(blank=True, null=True)),
                ('reserves_signal', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('brent_crude_usd', models.FloatField(blank=True, null=True)),
                ('oil_signal', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('cpi_yoy', models.FloatField(blank=True, null=True)),
                ('real_rate', models.FloatField(blank=True, null=True)),
                ('real_rate_signal', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('macro_stress_score', models.IntegerField(default=0)),
                ('composite_signal', models.CharField(choices=[('CALM', 'Calm'), ('WATCH', 'Watch'), ('STRESSED', 'Stressed'), ('PEAK_STRESS', 'Peak Stress')], default='CALM', max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Macro Warnings',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='cronlog',
            name='name',
            field=models.CharField(choices=[('update_prices', 'Price Update'), ('update_dividends', 'Dividend Update'), ('process_notifications', 'Notifications'), ('update_macro', 'Macro Update')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='MacroConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kse100_forward_pe', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Macro Config',
            },
        ),
    ]
