# Generated by Django 6.0.4 on 2026-04-17 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_index_remove_stock_kmi_30_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_date', models.DateField()),
                ('dividend_type', models.CharField(choices=[('cash', 'Cash Dividend'), ('bonus', 'Bonus Shares'), ('right', 'Right Shares'), ('mixed', 'Cash + Bonus')], max_length=10)),
                ('cash_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('bonus_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('raw_dividend', models.CharField(blank=True, max_length=50)),
                ('raw_bonus', models.CharField(blank=True, max_length=100)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='stocks.stock')),
            ],
            options={
                'verbose_name_plural': 'Dividends',
                'ordering': ['-ex_date'],
                'unique_together': {('stock', 'ex_date')},
            },
        ),
    ]
