# Generated by Django 6.0.4 on 2026-04-17 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_dividend'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurificationRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('period', models.CharField(max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('source_document', models.CharField(blank=True, max_length=100)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purification_ratios', to='stocks.stock')),
            ],
            options={
                'verbose_name_plural': 'Purification Ratios',
                'ordering': ['-effective_from'],
                'unique_together': {('stock', 'effective_from')},
            },
        ),
    ]
